version: 2
updates:
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "weekly"
      time: "06:00"
    open-pull-requests-limit: 5
    target-branch: "develop"
    commit-message:
      prefix: "FTD-BOT"
    labels: ["dependencies"]
    reviewers: 
      - "pukanszkypeter"

  - package-ecosystem: "gradle"
    directory: "backend/"
    schedule:
      interval: "weekly"
      time: "06:00"
    open-pull-requests-limit: 5
    target-branch: "develop"
    commit-message:
      prefix: "FTD-BOT"
    labels: ["dependencies"]
    reviewers: 
      - "pukanszkypeter"