version: 2
updates:
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "daily"
      time: "12:00"
    open-pull-requests-limit: 5
    target-branch: "develop"

  - package-ecosystem: "gradle"
    directory: "backend/"
    schedule:
      interval: "daily"
      time: "12:00"
    open-pull-requests-limit: 5
    target-branch: "develop"