version: '3.8'

services:
  # MySQL Database
  db:
   image: mysql
   command: --default-authentication-plugin=mysql_native_password
   environment:
     MYSQL_DATABASE: 'backend'
     MYSQL_USER: 'backend'
     MYSQL_PASSWORD: 'backend'
     MYSQL_ROOT_PASSWORD: 'root'
   healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p", "root"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
   ports:
     - "3306:3306"
   expose:
     - "3306"
   volumes:
     - ./docker/my-db:/var/lib/mysql
  
  # Database Manager
  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: 'dracula'
    ports:
      - 9000:8080
  
volumes:
  my-db:
    external: true
