export enum AlgorithmType {
  RANDOM = "RANDOM",
  RANDOM_LEADER = "RANDOM_LEADER",
  ROTOR_ROUTER = "ROTOR_ROUTER",
  ROTOR_ROUTER_LEADER = "ROTOR_ROUTER_LEADER",
  FAULTLESS_DFS = "FAULTLESS_DFS",
  FAULTY_DFS = "FAULTY_DFS",
}
