package engine.app.dto;

public enum AlgorithmType {
    RANDOM_DISPERSION,
    RANDOM_WITH_LEADER_DISPERSION,
    ROTOR_ROUTER_DISPERSION,
    ROTOR_ROUTER_WITH_LEADER_DISPERSION,
    FAULTLESS_DFS_DISPERSION,
    FAULTY_DFS_DISPERSION
}
