export enum AlgorithmType {
  RANDOM_DISPERSION = 'RANDOM_DISPERSION',
  RANDOM_WITH_LEADER_DISPERSION = 'RANDOM_WITH_LEADER_DISPERSION',
  ROTOR_ROUTER_DISPERSION = 'ROTOR_ROUTER_DISPERSION',
  ROTOR_ROUTER_WITH_LEADER_DISPERSION = 'ROTOR_ROUTER_WITH_LEADER_DISPERSION',
}
