#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo -e "\n|-----PRE-COMMIT-----|\n"

echo -e "🐶 Husky pre-commit hook running...\n"

cd frontend

echo -e "✏️  Formatting frontend code..."
npm run format:frontend -- --loglevel silent

echo -e "✏️  Formatting backend code..."
npm run format:backend -- --loglevel silent

echo -e "📜 Setting version...\n"
npm version $(cat ../.version) --allow-same-version

cd ..

echo -e "\n💾 Git saved changes.\n"
git add .

echo -e "\n✅ Pre-Commit hook was successful.\n"