export enum GraphType {
  BARABASI_ALBERT_FOREST = "BARABASI_ALBERT_FOREST",
  BARABASI_ALBERT_GRAPH = "BARABASI_ALBERT_GRAPH",
  BARBELL = "BARBELL",
  COMPLETE = "COMPLETE",
  GNM_RANDOM = "GNM_RANDOM",
  GNP_RANDOM = "GNP_RANDOM",
  GRID = "GRID",
  HYPER_CUBE = "HYPER_CUBE",
  LINEAR = "LINEAR",
  LOLLIPOP = "LOLLIPOP",
  RING = "RING",
  RANDOM_REGULAR = "RANDOM_REGULAR",
  STAR = "STAR",
  WHEEL = "WHEEL",
  WINDMILL = "WINDMILL",
}

export enum WindmillMode {
  WINDMILL = "WINDMILL",
  DUTCHWINDMILL = "DUTCHWINDMILL",
}
