name: Auto Releases

on:
  pull_request:
    types:
      - closed
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: release-please-action
          